# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0002_auto_20161213_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
