# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursesapp', '0003_auto_20161213_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coursesapp.Description'),
        ),
    ]
